# Generated by Django 5.2.7 on 2025-11-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalmind_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelexAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='goal_mind', max_length=100)),
                ('agent_id', models.CharField(default='goal_agent_001', max_length=50, unique=True)),
                ('description', models.TextField(default='A goal assistant that helps users create and track goals.')),
                ('category', models.CharField(default='productivity', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('short_description', models.CharField(default='Breaks goals into actionable steps', max_length=150)),
                ('long_description', models.TextField(default='I am a helpful goal-setting assistant. My primary function is to help users set and track personal goals by breaking them into achievable steps. Always respond with encouragement and clarity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='goals',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goalmind_app.telexagent'),
        ),
    ]
