# Generated by Django 5.2.7 on 2025-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalmind_app', '0002_telexagent_goals_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telexagent',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
